### ISSUE TITLE
Locura missing objective with Always Combat Turns

### ISSUE THREAD

**Issue by perkinslr** [BattletechModders/RogueTech#1534]
I'm running a handful of mods out of this repository with 1.8 (just the mechanical ones which load without errors).  I just came across a bug with the Locura mission and always combat turns.  Specifically, an objective is supposed to be added when the first enemy comes into sight and it moves from non-combat to combat turns.  With the always combat turns mod, this transition doesn't happen, so the objective doesn't get added to the tracker.  Since it doesn't get added to the tracker, it doesn't get completed, and the mission doesn't end after the 10 turn countdown.

I know RT isn't ready for a public 1.8 release, but I hope I can save you from the time needed to conduct a binary search which mod causes the inability to finish the mission.  

Both the Always Combat Turns mod, and the old CBTBehaviors cause it to start in combat mode.  I don't know if CBTBehaviorsEnhanced does too, because it doesn't load cleanly for me at the moment.

**Comment by LadyAlekto** [comment]
Well thats why youre not supposed to play locura or take pieces out of this blindly we know the issue very well

**Comment by LadyAlekto** [comment]
Closing because this is not a roguetech bug
