### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Dzhimar** [BattletechModders/RogueTech#1858]
your Weapon_COIL_COIL_0-STOCK file doesn't work.

**Comment by LadyAlekto** [comment]
Dare to explain to me why you are accessing a blacklisted file thats not used for rt and only exists to prevent the vanilla item?

**Comment by Rumialumia** [comment]
Arent the coils purposfully broken since they are op as hell?

**Comment by LadyAlekto** [comment]
Na, they just wont work in our framework, intentionally
