### ISSUE TITLE
1.6.3 ai freeze

### ISSUE THREAD

**Issue by anonymous555** [BattletechModders/RogueTech#2044]
Everything was working just fine in the 1.6.2 release prior to this one.

Now as soon as the AI takes it first move,  the AI never finishes.  I don't even see the circle moving indicating that the AI is thinking.  This happens every time it seems (ally or enemy).

**Comment by Raza5** [comment]
Why have you posted on our GitHub and not on Discord? We can't provide support over GitHub and we definitely can't provide support without logs or evidence beyond a single claim.

**Comment by Raza5** [comment]
Incidentally, this has just been hotfixed so an update will fix the issue
