### ISSUE TITLE
You See Ivan When To Firing All The Debuffs...

### ISSUE THREAD

**Issue by neonailol** [BattletechModders/RogueTech#3176]
Hey, in the game I came across a vehicle name "You See Ivan When To Firing All The Debuffs..."
I think this is a mistake and the name should be "Firetruck Ivan"

**Comment by Raza5** [comment]
This is an intended unit name and community meme/joke. We have no plans to change or edit this particular name at this time

**Comment by neonailol** [comment]
okay than :)
