### ISSUE TITLE
Needed gear/renaming for Battle Armour and Industrial mechs

### ISSUE THREAD

**Issue by Raza5** [BattletechModders/RogueTech#331]
[Battle Armour weapons and systems.txt](https://github.com/BattletechModders/RogueTech/files/3003939/Battle.Armour.weapons.and.systems.txt)
[Needed mech parts.txt](https://github.com/BattletechModders/RogueTech/files/3003940/Needed.mech.parts.txt)

**Comment by IVIilitarus** [comment]
Hey there,, if you can clarify what needs to be done, I might be able to help

**Comment by LadyAlekto** [comment]
new gear created from scratch

This is basically here to remind me to make them

I just need the muse to make the gameplay wise fitting and unique
