### ISSUE TITLE
Light AA Missile Rack tagged as [MeleeWeapon, Suicide Weapon]

### ISSUE THREAD

**Issue by giorgiga** [BattletechModders/RogueTech#4479]
![20210621164922_1](https://user-images.githubusercontent.com/471835/122790016-303c3680-d2b8-11eb-9d85-e8a1f6d00f82.jpg)

I'm not sure if this has any specific game effects (never used that weapon) - I'm just reporting this as it doesn't seem to make sense,

**Comment by LadyAlekto** [comment]
Why are you not creating tickets on discord?

**Comment by giorgiga** [comment]
@LadyAlekto 

Well... I never used discord and don't have an account there (tbh I didn't even know discord had tickets... I guess it's more than a chat then).

I kinda just saw the "issues" section here and assumed it was an ok way to open tickets :grin: so... no specific reason for using github beyond me already having an account here and not wanting to sign up to yet another service.
