### ISSUE TITLE
Next save break

### ISSUE THREAD

**Issue by Raza5** [BattletechModders/RogueTech#551]
Fix Locust IIC3 and Stinger IIC2 to correct naming scheme. Prune hardpoints of IIC3 Locust in line with other IIC mechs.

**Comment by Eternus8** [comment]
I add also to change Kingcrab 0001 to 001 and 0002 to 002 (actual lore variant the 001 and the 002 could be aswell)
shadowhawk -SHD-Ki also needs to be changed to SHD-K
