### ISSUE TITLE
Fire Shaders Not Working on M1

### ISSUE THREAD

**Issue by sirwolfgang** [BattletechModders/RogueTech#6881]
I am running RogueTech via Wine64 on OSX 12.4 (M1) and get purple with the old and new fire shader settings. 

Looking at the configuration, it seems like these are being loaded from a set of shaders. Where is this list enumerated? I want to try some other shaders and see if something works. 

Additionally, is it possible to add new shaders to BattleTech? It's been a few years since I've done shader code, but I could also try to write up or fix up a fire shader if someone can direct me where to start?

**Comment by CMiSSioN** [comment]
"Old" and "new" fire VFXs differ not only shaders - it is different prefabs loaded from different places. Also "old" and "new" terms are not correct. "Old" is spawning from prefab shipped with game, "new" from external assets bundle. Also there are no place where all shaders are kept in Unity. Each asset bundle contains own shaders list, even if it is literally same shader different assets bundles will have their own instance.  If you have fail in build-in shader - things are very bad. 
Answering your first question - no, there are no place where all shaders are listed.
Answering your second question - it is possible to load new assets bundles, new assets bundles can contain new shaders but they will have no influence on shaders already loaded. To replace shaders on existing objects you have to write code. For example right after model spawn like CustomUnits do with external units models. 
Also even "new" fire VFX is using particle effect with shader shipped with Unity itself, there are no sources for it. 
Sorry if being unhelpful, but reality is not always get us what we want

**Comment by sirwolfgang** [comment]
This issue self-resolved a few patches ago. Not sure why.
